---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-bordns-cm
  labels:
    app: {{ include "fullname" . }}
data:
  config.yml: |-
    etcd_hosts:
      - {{ .Release.Name }}-etcd-svc:2379

    auth_username: {{ .Values.conf.auth.username }}
    auth_password: {{ .Values.conf.auth.password }}

    listen_address: ":8000"

    zones:
     {{range .Values.conf.zones -}}
      - zone: {{ .zone | quote }}
       path: {{ .path | quote }}
     {{ end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-coredns-cm
  labels:
    app: {{ include "fullname" . }}
data:
  Corefile: |-
        .:53 {
                log
                errors
                prometheus 0.0.0.0:9100
        }
        {{range .Values.conf.zones -}}
        {{ .zone }} {
                log
                errors
                etcd  {
                        path {{ .path }}
                        endpoint http://{{ $.Release.Name }}-etcd-svc:2379
                }
        }
        {{ end}}
