---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-deployment
  labels:
    app: {{ include "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      volumes:
        - name: {{ include "fullname" . }}-bordns-cm
          configMap:
            name: {{ include "fullname" . }}-bordns-cm
        - name: {{ include "fullname" . }}-coredns-cm
          configMap:
            name: {{ include "fullname" . }}-coredns-cm
      containers:
        - name: bordns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG
              value: /conf/config.yml
          volumeMounts:
            - name: {{ include "fullname" . }}-bordns-cm
              mountPath: /conf/config.yml
              subPath: config.yml

        - name: coredns
          image: "coredns/coredns:latest"
          ports:
            - containerPort: 9100
            - containerPort: 53
          volumeMounts:
            - name: {{ include "fullname" . }}-coredns-cm
              mountPath: /root/Corefile
              subPath: Corefile
          args: ["-conf", "/root/Corefile"]
