version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd
    volumes:
      - ./docker/etcd-entrypoint.sh:/entrypoint.sh
    command: sh /entrypoint.sh
    networks:
      dnsnet:
        ipv4_address: 172.19.0.3
  dns:
    image: coredns/coredns
    volumes:
      - ./docker/coredns_config/Corefile:/root/Corefile
    command: -conf /root/Corefile
    networks:
      dnsnet:
        ipv4_address: 172.19.0.2
  bordns:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      dnsnet:
        ipv4_address: 172.19.0.4
    volumes:
      - ./docker/bordns_config/config.yml:/config.yml
        #    ports:
        #      - "8000:8000"


networks:
  dnsnet:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

