---
{{- if .Values.storage.persist }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "fullname" . }}-sc
  mountOptions:
    - hard
  nfs:
    path: {{ .Values.storage.nfs.path  }}
    server: {{ .Values.storage.nfs.server  }}
{{- end }}
