---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-svc
spec:
  type: ClusterIP
  ports:
    - name: etcd
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: {{ include "fullname" . }}
