---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bordns-deployment
  namespace: bordns
  labels:
    app: dns
spec:
  selector:
    matchLabels:
      app: dns
  replicas: 1
  template:
    metadata:
      labels:
        app: dns
    spec:
      volumes:
        - name: data
          nfs:
            server: 10.0.1.30
            path: /mnt/horus/k8-data/bordns
        - name: corefile
          secret:
            secretName: corefile-secret
        - name: bordns-config
          secret:
            secretName: bordns-secret

      containers:
        - name: bordns
          image: hub.sekhnet.ra/bordns
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG
              value: /conf/config.yml
          volumeMounts:
            - name: bordns-config
              mountPath: /conf/config.yml
              subPath: config.yml

        - name: coredns
          image: coredns/coredns
          ports:
            - containerPort: 53
          volumeMounts:
            - name: corefile
              mountPath: /root/Corefile
              subPath: Corefile
          args: ["-conf", "/root/Corefile"]

        - name: etcd
          image: quay.io/coreos/etcd:latest
          volumeMounts:
            - name: data
              mountPath: /var/run/etcd
          command:
            - /bin/sh
            - -c
            - |
                etcd --name etcd \
                --listen-client-urls=http://0.0.0.0:2379 \
                --listen-peer-urls=http://localhost:2380 \
                --advertise-client-urls=http://0.0.0.0:2379 \
                --initial-cluster-token=etcd-cluster-1 \
                --initial-cluster=etcd=http://localhost:2380 \
                --initial-cluster-state=new \
                --data-dir=/var/run/etcd/default.etcd
