---
apiVersion: v1                                                                   
kind: PersistentVolumeClaim                                                      
metadata:
  name: etcd-pvc
  namespace: bordns
spec:
  storageClassName: k8-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi                                                               

