---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc
  namespace: bordns 
  labels:
    app: dns
spec:
  selector:
    app: dns
  externalIPs:
    - 10.0.1.253
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
