---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc
  namespace: bordns 
  labels:
    app: dns
spec:
  selector:
    app: dns
  externalIPs:
    - 10.0.1.253
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    
---
# This is only for the kube-system coredns accessing etcd
apiVersion: v1
kind: Service
metadata:
  name: etcd-dns-svc
  namespace: bordns 
  labels:
    app: dns
spec:
  selector:
    app: dns
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
