apiVersion: v1
data:
  Corefile: ".:53 {\n\tlog \n\terrors\n}\n\n{{ .Values.defaultZone }} {\n\tlog \n\terrors\n\tetcd  {\n\t\tpath /{{ .Values.defaultZone }}\n\t\tendpoint http://127.0.0.1:2379\n\t}\n}\n\n\n"
kind: ConfigMap
metadata:
  name: dns-corefile-cm
