---
apiVersion: v1                                                                   
kind: PersistentVolumeClaim                                                      
metadata:
  name: etcd-pvc
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi                                                               

