---
apiVersion: v1
kind: Service
metadata:
  name: dns-svc
  labels:
    app: dns
spec:
  selector:
    app: dns
  externalIPs:
    - {{ .Values.serviceIP }}
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: etcd
      protocol: TCP
      port: 2379
      targetPort: 2379
