---
bordns:
  image:
    repository: hub.sekhnet.ra/bordns
    pullPolicy: Always
    tag: "latest"

  service:
    type: LoadBalancer
    bordnsLoadBalancerIP: 10.0.1.212
    dnsLoadBalancerIP: 10.0.1.213
    port: 80

  conf:
    auth:
      username: user
      password: password
    zones:
      - zone: bor
        path: /bor
      - zone: sekhnet.ra
        path: /ra/sekhnet

etcd:
  storage:
    persist: false
    nfs:
      path: /
      server: 10.0.0.1
    size: 1Gi
