# Default values for bordns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


bordns:
  image:
    repository: hub.sekhnet.ra/bordns
    pullPolicy: Always
    tag: "latest"

  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.212
    port: 80

  conf:
    auth:
      username: user
      password: password
    zones:
      - zone: bordns.ra
        path: /ra/bordns

coredns:
  image:
    repository: coredns/cordns
    pullPolicy: Always
    # Overrides the image tag whose default is the chart version.
    tag: ""

  service:
    type: LoadbalancerIP
    loadBalancerIP: 10.0.1.213
    port: 80
